#!/usr/bin/perl -w

# Makes mosaics that contain 20 fields for OB processing

@mosaics=(
["G2","ga2","ga7","ha2","ha7","f9","g4","g9","h4","g1","g6","h1","h6","f8","g3","g8","h3","g0","g5","h0","h5",104.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6]
);

$ap=chr(34);
$sap=chr(39);

for ($i = 0; $i <= 0; $i++) {

$mos="M"."$mosaics[$i][0]";
$moslc= lc $mos;
$long="$mosaics[$i][21]";
$lat="$mosaics[$i][22]";

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics/";
system("mkdir $mos");

$band="a";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="a";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

}

sub makemos {

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics/$mos";
system("mkdir $band");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics/$mos/$band";
system("mkdir $stokes");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics/$mos"."/$band"."/$stokes";

open(getfiles, "|madr");
print getfiles "rdir\n"; #!
print getfiles "../../../../PRC/"."$mosaics[$i][1]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][2]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][3]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][4]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][5]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][6]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][7]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][8]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][9]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][10]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][11]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][12]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][13]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][14]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][15]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][16]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][17]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][18]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][19]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][20]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f16\n";
print getfiles "n\n";#!
print getfiles "nam\n";
print getfiles ".\n";
print getfiles "exit\n"; #!
close(getfiles);


open(supermos, "|supertile");
print supermos "\n";  #! Do you wish to run in batch mo
print supermos "\n";  #! Do you want to create a log? [
print supermos "\n";  #! Is log file to be printed on e
print supermos "\n";  #! Run in debug mode? [N]:
print supermos "\n";  #! Display elapsed times on termi
print supermos "\n";  #! Are you adding new datasets to
print supermos "\n";  #! Are oversize input datasets to
print supermos "l\n";  #! Select max. number of input da
print supermos "n\n";  #! Are datacubes (rather than sin
print supermos "\n";  #! Type to be used [3]:
print supermos "\n";  #! Are a resolution datacube and
print supermos "\n";  #!  Are only these beam products
print supermos "\n";  #! Desired weighting scheme [1]:
print supermos "\n";  #! Are polar diagrams assumed to
print supermos "\n";  #! Are all polar diagrams centred
print supermos "\n";  #! Are input datasets to be corre
print supermos "\n";  #! Are registration corrections t
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "1\n";  #!   File definition number [DEFI
print supermos "\n";  #! Can this default value be adop
print supermos "\n";  #! Are weights to be set to zero
print supermos "\n";  #! Can one radius be adopted for
print supermos "75\n";  #!  Radius to zero weights beyond
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "2\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "3\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "4\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "5\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "6\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "7\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "8\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "9\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "10\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "11\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "12\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "13\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "14\n";  #!   File definition number [DEFI
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "15\n";  #!   File definition number [DEFI
print supermos "n\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".mos\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #! Data type (IRD) [R]:
print supermos "1024 1024\n";  #! Basic element and record dimen
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "g\n";  #! Sky projection (SEGTVACF) [S]:
print supermos "f\n"; #! Select velocity-like coordinat
print supermos "$long"."D\n";  #! LONGITUDE of reference element
print supermos "$lat"."D\n";  #! LATITUDE of reference record [
print supermos "\n";  #! Reference ELEMENT for longitud
print supermos "\n";  #! Reference RECORD for latitude
print supermos "18"."$ap\n";  #! DELTA LONGITUDE per element (u
print supermos "18"."$ap\n";  #! DELTA LATITUDE per record (uns
print supermos "\n";  #! Define file (3rd dimension) co
print supermos "\n";  #! Define resolution (beam and ve
print supermos "2020.0\n"; #! Observation epoch (e.g. 1984.6
print supermos "\n";  #! Are the entered astrophysical
print supermos "\n";  #! Do you want a comment? [N]:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! Do you wish to continue? [Y]:
print supermos "\n";  #!   brightness-temperature scale
print supermos "\n";  #! Record interval ( >= 64 ) for
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".wt\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".res@@\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".bp\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! C:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! just in case...
close(supermos);
}

