#!/usr/bin/perl -w

# Makes GMIMS regridded mosaics that contain 18 fields
# Adapted from earlier scripts, AO February 2023

@mosaics=(
["H2","ha2","ha7","h4","h9","i4","i9","h1","h6","i1","i6","h3","h8","i3","i8","h0","h5","i0","i5",100.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["O2","n4","n9","o4","o4s","o9s","o6s","n6","o1","o6","p1","n3","n8","o3","o8","n5","o0","o5","p0",76.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["EJ1","ej1","ej6","ek1","r8","ej3","ej8","ek3","ej0","ej5","ek0","ek5","r7","ej2","ej7","ek2","rr22","ob11","ob12",60.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["R2","ob10","sn02","sn01","q9","r4","r9","ej4","q6","r1","r6","ej1","q8","r3","r8","ej3","r0","r5","ej0",64.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6]
);

$ap=chr(34);
$sap=chr(39);

for ($i = 0; $i <= 3; $i++) {

$mos="M"."$mosaics[$i][0]";
$moslc= lc $mos;
$long="$mosaics[$i][19]";
$lat="$mosaics[$i][20]";

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/";
system("mkdir $mos");

$band="a";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="a";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

}

sub makemos {

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos";
system("mkdir $band");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos/$band";
system("mkdir $stokes");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos"."/$band"."/$stokes";

open(getfiles, "|madr");
print getfiles "rdir\n"; #!
print getfiles "../../../../PRC/"."$mosaics[$i][1]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][2]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][3]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][4]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][5]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][6]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][7]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][8]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][9]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][10]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][11]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][12]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][13]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][14]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][15]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][16]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][17]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][18]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "nam\n";
print getfiles ".\n";
print getfiles "exit\n"; #!
close(getfiles);


open(supermos, "|supertile");
print supermos "\n";  #! Do you wish to run in batch mo
print supermos "\n";  #! Do you want to create a log? [
print supermos "\n";  #! Is log file to be printed on e
print supermos "\n";  #! Run in debug mode? [N]:
print supermos "\n";  #! Display elapsed times on termi
print supermos "\n";  #! Are you adding new datasets to
print supermos "\n";  #! Are oversize input datasets to
print supermos "l\n";  #! Select max. number of input da
print supermos "n\n";  #! Are datacubes (rather than sin
print supermos "\n";  #! Type to be used [3]:
print supermos "\n";  #! Are a resolution datacube and
print supermos "\n";  #!  Are only these beam products
print supermos "\n";  #! Desired weighting scheme [1]:
print supermos "\n";  #! Are polar diagrams assumed to
print supermos "\n";  #! Are all polar diagrams centred
print supermos "\n";  #! Are input datasets to be corre
print supermos "\n";  #! Are registration corrections t
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "1\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]:
print supermos "$freq\n"; #! Enter frequency (MHz) for polar diagram (408/1420/other) [1420]:  
print supermos "\n"; #! Is there a value that can be adopted for all datasets? [Y]:  
print supermos "107.2\n"; #! Polar-diagram full half-power width (arcmin) [0.000]:
print supermos "\n";  #! Are weights to be set to zero
print supermos "\n";  #! Can one radius be adopted for
print supermos "75\n";  #!  Radius to zero weights beyond
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "2\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "3\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "4\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "5\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "6\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "7\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "8\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "9\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "10\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "11\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "12\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "13\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "14\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "15\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "n\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".mos\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #! Data type (IRD) [R]:
print supermos "1024 1024\n";  #! Basic element and record dimen
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "g\n";  #! Sky projection (SEGTVACF) [S]:
print supermos "f\n"; #! Select velocity-like coordinat
print supermos "$long"."D\n";  #! LONGITUDE of reference element
print supermos "$lat"."D\n";  #! LATITUDE of reference record [
print supermos "\n";  #! Reference ELEMENT for longitud
print supermos "\n";  #! Reference RECORD for latitude
print supermos "18"."$ap\n";  #! DELTA LONGITUDE per element (u
print supermos "18"."$ap\n";  #! DELTA LATITUDE per record (uns
print supermos "\n";  #! Define file (3rd dimension) co
print supermos "\n";  #! Define resolution (beam and ve
print supermos "2020.0\n"; #! Observation epoch (e.g. 1984.6
print supermos "\n";  #! Are the entered astrophysical
print supermos "\n";  #! Do you want a comment? [N]:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! Do you wish to continue? [Y]:
print supermos "\n";  #!   brightness-temperature scale
print supermos "\n";  #! Record interval ( >= 64 ) for
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".wt\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".res@@\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".bp\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! C:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! just in case...
close(supermos);

}

