#!/usr/bin/perl -w

# Makes GMIMS regridded mosaics that contain 16 fields
# Adapted from earlier scripts, AO February 2023

@mosaics=(
["ES1","er6","es1","es6","et1","er8","es3","es8","et3","er5","es0","es5","et0","er7","es2","es7","et2",184.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["ES2","er9","es4","es9","et4","er6","es1","es6","et1","er8","es3","es8","et3","er5","es0","es5","et0",184.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["P1","o6","p1","p6","q1","o8","p3","p8","q3","o5","p0","p5","q0","o7","p2","p7","q2",72.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["O1","n6","o1","o6","p1","n3","n8","o3","o8","n5","o0","o5","p0","n2","n7","o2","o7",76.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["F1","f1","f6","g1","e8","f3","f8","g3","xq2","f5","g0","g5","xq3","f7","g2","xq4","xq5",108.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["H1","h1","h6","i1","i6","h3","h8","i3","i8","h0","h5","i0","i5","h2","h7","i2","i7",100.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["G1","g1","g6","h1","h6","f8","g3","g8","h3","g0","g5","h0","h5","f7","g2","g7","h2",104.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["D2","ea2","c9","d4","d9","e4","d1","d6","e1","e6","c8","d3","d8","e3","d0","d5","e0",116.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["EZ1","ez1","ez6","s1","s6","ez3","ez8","s3","s8","ez0","ez5","s0","s5","ez2","ez7","s2","s7",156.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["EZ2","ez4","ez9","s4","s9","ez1","ez6","s1","s6","ez3","ez8","s3","s8","ez0","ez5","s0","s5",156.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["EY1","ey1","ey6","ez1","ez6","ex8","ey3","ey8","ez3","ey0","ey5","ez0","ez5","ex7","ey2","ey7","ez2",160.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["EY2","ex9","ey4","ey9","ez4","ey1","ey6","ez1","ez6","ex8","ey3","ey8","ez3","ey0","ey5","ez0","ez5",160.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["A1","y6","a1","a6","b1","y8","a3","a8","b3","y5","a0","a5","b0","y7","a2","a7","b2",128.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["A2","y9","a4","a9","b4","y6","a1","a6","b1","y8","a3","a8","b3","y5","a0","a5","b0",128.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["Y1","x6","y1","y6","a1","x3","x8","y3","y8","x5","y0","y5","a0","x2","x7","y2","y7",132.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["Y2","x4","x9","y4","y9","x6","y1","y6","a1","x3","x8","y3","y8","x5","y0","y5","a0",132.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6]
);

$ap=chr(34);
$sap=chr(39);

for ($i = 0; $i <= 15; $i++) {

$mos="M"."$mosaics[$i][0]";
$moslc= lc $mos;
$long="$mosaics[$i][17]";
$lat="$mosaics[$i][18]";

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/";
system("mkdir $mos");

$band="a";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][19]";
&makemos;

$band="a";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][19]";
&makemos;

$band="b";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][20]";
&makemos;

$band="b";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][20]";
&makemos;

$band="c";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][21]";
&makemos;

$band="c";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][21]";
&makemos;

$band="d";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][22]";
&makemos;

$band="d";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
$freq="$mosaics[$i][22]";
&makemos;

}

sub makemos {

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos";
system("mkdir $band");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos/$band";
system("mkdir $stokes");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos"."/$band"."/$stokes";

open(getfiles, "|madr");
print getfiles "rdir\n"; #!
print getfiles "../../../../PRC/"."$mosaics[$i][1]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][2]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][3]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][4]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][5]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][6]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][7]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][8]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][9]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][10]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][11]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][12]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][13]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][14]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][15]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][16]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "nam\n";
print getfiles ".\n";
print getfiles "exit\n"; #!
close(getfiles);

open(supermos, "|supertile");
print supermos "\n";  #! Do you wish to run in batch mo
print supermos "\n";  #! Do you want to create a log? [
print supermos "\n";  #! Is log file to be printed on e
print supermos "\n";  #! Run in debug mode? [N]:
print supermos "\n";  #! Display elapsed times on termi
print supermos "\n";  #! Are you adding new datasets to
print supermos "\n";  #! Are oversize input datasets to
print supermos "l\n";  #! Select max. number of input da
print supermos "n\n";  #! Are datacubes (rather than sin
print supermos "\n";  #! Type to be used [3]:
print supermos "\n";  #! Are a resolution datacube and
print supermos "\n";  #!  Are only these beam products
print supermos "\n";  #! Desired weighting scheme [1]:
print supermos "\n";  #! Are polar diagrams assumed to
print supermos "\n";  #! Are all polar diagrams centred
print supermos "\n";  #! Are input datasets to be corre
print supermos "\n";  #! Are registration corrections t
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "1\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]:
print supermos "$freq\n"; #! Enter frequency (MHz) for polar diagram (408/1420/other) [1420]:  
print supermos "\n"; #! Is there a value that can be adopted for all datasets? [Y]:  
print supermos "107.2\n"; #! Polar-diagram full half-power width (arcmin) [0.000]:
print supermos "\n";  #! Are weights to be set to zero
print supermos "\n";  #! Can one radius be adopted for
print supermos "75\n";  #!  Radius to zero weights beyond
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "2\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "3\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "4\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "5\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "6\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "7\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "8\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "9\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "10\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "11\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "12\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "13\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "14\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "15\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "16\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "n\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".mos\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #! Data type (IRD) [R]:
print supermos "1024 1024\n";  #! Basic element and record dimen
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "g\n";  #! Sky projection (SEGTVACF) [S]:
print supermos "f\n"; #! Select velocity-like coordinat
print supermos "$long"."D\n";  #! LONGITUDE of reference element
print supermos "$lat"."D\n";  #! LATITUDE of reference record [
print supermos "\n";  #! Reference ELEMENT for longitud
print supermos "\n";  #! Reference RECORD for latitude
print supermos "18"."$ap\n";  #! DELTA LONGITUDE per element (u
print supermos "18"."$ap\n";  #! DELTA LATITUDE per record (uns
print supermos "\n";  #! Define file (3rd dimension) co
print supermos "\n";  #! Define resolution (beam and ve
print supermos "2020.0\n"; #! Observation epoch (e.g. 1984.6
print supermos "\n";  #! Are the entered astrophysical
print supermos "\n";  #! Do you want a comment? [N]:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! Do you wish to continue? [Y]:
print supermos "\n";  #!   brightness-temperature scale
print supermos "\n";  #! Record interval ( >= 64 ) for
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".wt\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".res@@\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".bp\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! C:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! just in case...
close(supermos);

open(changefiles, "|madr");
print changefiles "d f17\n";#! ?>
print changefiles "\n";  #! File name (max 52 chars) [ME2A
print changefiles "\n";  #! Data type (IRD) [R]:
print changefiles "\n";  #! Dimensions:
print changefiles "\n";  #! Subset [NONE]:
print changefiles "\n";  #! Are "undefined" data allowed?
print changefiles "\n";  #!    Value to indicate "undefine
print changefiles "\n";  #!    Data-unit type [4]:
print changefiles "\n";  #!    Scaling factor [1.000]:
print changefiles "\n";  #! Are the parameters that you en
print changefiles "\n";  #! Define coordinates (astronomic
print changefiles "\n";  #! Type of file (RD,RV,VD,UV,XY)
print changefiles "\n";  #! Sky projection (SEGTVACF) [G]:
print changefiles "\n";  #! Select velocity-like coordinat
print changefiles "\n";  #! LONGITUDE of reference element
print changefiles "\n";  #! LATITUDE of reference record [
print changefiles "\n";  #! Reference ELEMENT for longitud
print changefiles "\n";  #! Reference RECORD for latitude
print changefiles "\n";  #! DELTA LONGITUDE per element (u
print changefiles "\n";  #! DELTA LATITUDE per record (uns
print changefiles "\n";  #! Define file (3rd dimension) co
print changefiles "\n";  #! Define resolution (beam and ve
print changefiles "\n";  #! Define auxiliary astronomical
print changefiles "$freq\n"; #! Central heliocentric frequency
print changefiles "\n";  #! Stokes parameter [Qgal] ("/?"
print changefiles "\n";  #! Data-set bandwidth (MHz) [7.50
print changefiles "\n";  #! Observation epoch (e.g. 1984.6
print changefiles "\n";  #! Are the entered astrophysical
print changefiles "\n";  #! Do you want a comment? [N]:
print changefiles "exit\n";  #! ?>
close(changefiles);

open(makefits, "|wfits");
print makefits "\n"; #! Do you want to create a log? [
print makefits "\n"; #! Is log file to be printed on e
print makefits "\n"; #! Are FITS images to be written
print makefits "n\n";  #!  in this run? [Y]:
print makefits "17\n";  #!   File definition number [DEFI
print makefits "\n"; #! Do you have a particular heade
print makefits "\n"; #! Do you want to write a bare mi
print makefits "$filename"."_GMIMS_image\n";  #! OBJECT name for image(s) [head
print makefits "n\n";  #! Are specific comments (<72 cha
print makefits "\n"; #! Are data antenna-beam values?
print makefits "d\n";  #! Hit RETURN to examine header,
print makefits "\n"; #! Do you want to save this heade
print makefits "\n"; #! Do you want to write header to
print makefits "\n"; #! Do you want to write header +
print makefits "$filename"."_GMIMS_image.fits\n";  #! Name of the FITS disk output f
print makefits "y\n";  #! Do you want to process another
print makefits "18\n";  #!   File definition number [DEFI
print makefits "\n"; #! Do you have a particular heade
print makefits "\n"; #! Do you want to write a bare mi
print makefits "$filename"."_GMIMS_wt\n";  #! OBJECT name for image(s) [head
print makefits "n\n";  #! Are specific comments (<72 cha
print makefits "\n"; #! Are data antenna-beam values?
print makefits "d\n";  #! Hit RETURN to examine header,
print makefits "\n"; #! Do you want to save this heade
print makefits "\n"; #! Do you want to write header to
print makefits "\n"; #! Do you want to write header +
print makefits "$filename"."_GMIMS_wt.fits\n";  #! Name of the FITS disk output f
print makefits "n\n";  #! Do you want to process another
close(makefits);

}

