#!/usr/bin/perl -w

# Makes mosaics that contain 19 fields for OB processing

@mosaics=(
["EK1","ek1","ek6","el1","ej8","ek3","ek8","el3","ek0","ek5","el0","el5","ej7","ek2","ek7","el2","ob11","ob12","ob13","ob14",56.75,-1.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["P2","o9s","ob08","ob09","p4","p9","q4","o6s","o6","p1","p6","q1","o8","p3","p8","q3","o5","p0","p5","q0",72.75,3.0,,1406.9,1413.8,1427.4,1434.3,1420.6],
["Q2","ob08","ob09","ob10","sn02","p9","q4","q9","r4","p6","q1","q6","r1","p8","q3","q8","r3","q0","q5","r0",68.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["E2","ea2","ea7","fa2","fa7","d9","e4","e9","f4","e1","e6","f1","f6","d8","e3","e8","f3","e0","xq1","xq2",112.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6],
["F2","fa2","fa7","ga2","ga7","e9","f4","f9","g4","f1","f6","g1","g6","e8","f3","f8","g3","f5","g0","xq2",108.75,3.0,1406.9,1413.8,1427.4,1434.3,1420.6]
);

$ap=chr(34);
$sap=chr(39);

for ($i = 4; $i <= 4; $i++) {

$mos="M"."$mosaics[$i][0]";
$moslc= lc $mos;
$long="$mosaics[$i][20]";
$lat="$mosaics[$i][21]";

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/";
system("mkdir $mos");

$band="a";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="a";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="b";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="c";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="q";
$filename="$moslc"."$band"."$stokes";
&makemos;

$band="d";
$stokes="u";
$filename="$moslc"."$band"."$stokes";
&makemos;

}

sub makemos {

chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos";
system("mkdir $band");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos/$band";
system("mkdir $stokes");
chdir "/home/ordoga/DRAO_export/CG_W23/Mosaics_G/$mos"."/$band"."/$stokes";

open(getfiles, "|madr");
print getfiles "rdir\n"; #!
print getfiles "../../../../PRC/"."$mosaics[$i][1]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][2]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][3]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][4]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][5]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][6]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][7]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][8]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][9]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][10]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][11]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][12]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][13]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][14]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][15]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][16]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][17]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][18]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "rdir\n";#!
print getfiles "../../../../PRC/"."$mosaics[$i][19]"."p21/"."$band"."/$stokes\n";#!
print getfiles "rget f12\n";
print getfiles "n\n";#!
print getfiles "nam\n";
print getfiles ".\n";
print getfiles "exit\n"; #!
close(getfiles);


open(supermos, "|supertile");
print supermos "\n";  #! Do you wish to run in batch mo
print supermos "\n";  #! Do you want to create a log? [
print supermos "\n";  #! Is log file to be printed on e
print supermos "\n";  #! Run in debug mode? [N]:
print supermos "\n";  #! Display elapsed times on termi
print supermos "\n";  #! Are you adding new datasets to
print supermos "\n";  #! Are oversize input datasets to
print supermos "l\n";  #! Select max. number of input da
print supermos "n\n";  #! Are datacubes (rather than sin
print supermos "\n";  #! Type to be used [3]:
print supermos "\n";  #! Are a resolution datacube and
print supermos "\n";  #!  Are only these beam products
print supermos "\n";  #! Desired weighting scheme [1]:
print supermos "\n";  #! Are polar diagrams assumed to
print supermos "\n";  #! Are all polar diagrams centred
print supermos "\n";  #! Are input datasets to be corre
print supermos "\n";  #! Are registration corrections t
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "1\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]:
print supermos "$freq\n"; #! Enter frequency (MHz) for polar diagram (408/1420/other) [1420]:  
print supermos "\n"; #! Is there a value that can be adopted for all datasets? [Y]:  
print supermos "107.2\n"; #! Polar-diagram full half-power width (arcmin) [0.000]:
print supermos "\n";  #! Are weights to be set to zero
print supermos "\n";  #! Can one radius be adopted for
print supermos "75\n";  #!  Radius to zero weights beyond
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n";  #!   Relative RMS noise (after sc
print supermos "2\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "3\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "4\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "5\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "6\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "7\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "8\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "9\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "10\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "11\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "12\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "13\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "14\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   Scale factor [1.000]:
print supermos "\n"; #!   Relative RMS noise (after sc
print supermos "15\n";  #!   File definition number [DEFI
print supermos "y\n"; #! Do you wish to change the defin
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "36"."$sap"." 0.00"."$ap\n";  #! Major width [0' 0.00"]: 
print supermos "0.000D\n"; #! Orientation angle (CCW from longitude axis) [0.000D]: 
print supermos "\n"; #! Frequency (MHz) resolution [0.000]: 
print supermos "\n"; #! Do you want to save the modified definition? [N]: 
print supermos "n\n";  #! Add another dataset? [Y]:
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".mos\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #! Data type (IRD) [R]:
print supermos "1024 1024\n";  #! Basic element and record dimen
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "g\n";  #! Sky projection (SEGTVACF) [S]:
print supermos "f\n"; #! Select velocity-like coordinat
print supermos "$long"."D\n";  #! LONGITUDE of reference element
print supermos "$lat"."D\n";  #! LATITUDE of reference record [
print supermos "\n";  #! Reference ELEMENT for longitud
print supermos "\n";  #! Reference RECORD for latitude
print supermos "18"."$ap\n";  #! DELTA LONGITUDE per element (u
print supermos "18"."$ap\n";  #! DELTA LATITUDE per record (uns
print supermos "\n";  #! Define file (3rd dimension) co
print supermos "\n";  #! Define resolution (beam and ve
print supermos "2020.0\n"; #! Observation epoch (e.g. 1984.6
print supermos "\n";  #! Are the entered astrophysical
print supermos "\n";  #! Do you want a comment? [N]:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! Do you wish to continue? [Y]:
print supermos "\n";  #!   brightness-temperature scale
print supermos "\n";  #! Record interval ( >= 64 ) for
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".wt\n"; #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".res@@\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #!   File definition number [DEFI
print supermos "$filename".".bp\n";  #! File name (max 52 chars) [] ("
print supermos "\n";  #!    Value to indicate "undefine
print supermos "\n";  #! Are the parameters that you en
print supermos "\n";  #! C:
print supermos "\n";  #! Do you want to save this defin
print supermos "\n";  #! just in case...
close(supermos);

}

